### ISSUE TITLE
Is it working with storcube s1000?

### ISSUE THREAD

**Issue by DarKOrange75** [fwPunsher/batteryMqtt#1]
Hello,
Thank you for your work. Do you think it would work with a Storcube S1000 battery and what could be the parameters for this battery ?

thank you !

**Comment by fwPunsher** [comment]
Hi,
probably yes. Parameters should be the default ones except the APPCODE.
You could try and guess. Probably something with "Storecube" or so.
To find the actual value I used PCAPDroid (Android) and checked the connection of the A-Solar App. Its in there in cleartext.

Regards

**Comment by DarKOrange75** [comment]
Hi,

Thank you for your answer, I will try :-)

Regards

Edit: APPCODE is "Storcube"

**Comment by fwPunsher** [comment]
So I take it that it's working for you?

**Comment by DarKOrange75** [comment]
Yes it is, thanks to your help 👍

**Comment by DarKOrange75** [comment]
Yes it is, thanks to your help 👍

**Comment by DarKOrange75** [comment]
Yes it is, thanks to your help 👍
