### ISSUE TITLE
Home Assistant custom component

### ISSUE THREAD

**Issue by DarKOrange75** [fwPunsher/batteryMqtt#2]
Hi,

Do you think it is possible to make a Home Assistant custom component from your script?

Thank you for your help!

**Comment by fwPunsher** [comment]
Hey, 

since it publishes to MQTT you should have all options to integrate it into home assistant. But I myself am running openhab. So I am not that deep into home assistant to provide it to you.

Regards

**Comment by DarKOrange75** [comment]
Thank you 👍
